main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.signup, name='signup'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')
    
def home(request):
    return render(request, 'main/home.html')

def signup(request):
    if(request.method == "POST"):
        name = request.POST['username']
        email = request.POST['email']
        passs = request.POST['password']
        user = User.objects.create_user(name, email, passs)
        user.save()
        return HttpResponseRedirect('/login')
    else:
        return render(request, 'main/signup.html')


def log_in(request):
    if (request.method == "POST"):
        name = request.POST['username']
        passs = request.POST['password']
        user = authenticate(request, username=name, password=passs)
        success = False
        if user is not None:
            login(request, user)
            success = True
            return render(request, 'main/home.html', {'success':success})
        
        else:
            
            return render(request, 'main/login.html', {'success':success})
    else:  

        return render(request, 'main/login.html')

main/templates/main/home.html
{% extends 'base.html' %}


{% block meta %}
<title>Story 9</title>
<style>
    p{
        text-align: center;
    }

    body{
      background-color:#B9F2FF;
    }
    
</style>
{% endblock meta %}

{% block content %}
{% if user.is_authenticated %}
<h2 style="text-align: center;">Hi, {{ user.username }}!</h2>
<p><a href="{% url 'main:logout' %}">Log Out</a></p>
{% else %}
<h2 style="text-align: center;">You are not logged in</h2>
<p><a href="{% url 'main:login' %}">Log In</a></p>
{% endif %}
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<style>
    .form-container{
        padding:10;
        position:relative;
        top:5%;
        width:50%;
        margin:auto;
    }
    p{
        text-align: center;
    }

    body{
      background-color:#B9F2FF;
    }
    
    
</style>
{% endblock meta %}

{% block content %}
<form action="{% url 'main:login' %}" method="post">
    {% csrf_token %}
    <div class="form-container">
        <h2>Log in</h2>   
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Username" name="username" id="username">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
            </div>
            <input type="password" class="form-control" placeholder="Password" name="password" id="password">
        </div>
        <button type="submit" class="btn btn-dark">Log in</button>
    {% if success == False %}
    <p style="color: red;">The credentials you are using are invalid</p>
    {% endif %}
    <p></p>
    <p>Don't have an account yet? <a href="{% url 'main:signup' %}">Sign Up</a></p>
    </div>
</form>
{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<style>
    .form-container{
        padding:10;
        position:relative;
        top:5%;
        width:50%;
        margin:auto;
    }

    p{
        text-align: center;
    }

    body{
      background-color:#B9F2FF;
    }
    
</style>
{% endblock meta %}

{% block content %}
<form action="{% url 'main:signup' %}" method="post">
    {% csrf_token %}
    <div class="form-container">
        <h2>Create Account</h2>   
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Username" name="username" id="username"><br>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-at"></i></span>
            </div>
            <input type="email" class="form-control" placeholder="E-mail" name="email" id="email"><br>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
            </div>
            <input type="password" class="form-control" placeholder="Password" name="password" id="password"><br>
        </div>
        <button type="submit" class="btn btn-dark">Sign Up</button>

        <p></p>
        <p>Already have an account? <a href="{% url 'main:login' %}">Log in</a></p>
    </div>
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>